cnp_settings:
  training_epochs: 1
  context_ratio: 0.3333333
  context_is_subset: True
  batch_size_train: 3000
  files_per_batch_train: 50
  batch_size_predict: [50000,10000000]
  files_per_batch_predict: 1
  number_of_walkers: 1
  config_wise: False
  use_data_augmentation: "mixup" #"smote" #False #"mixup"
  use_beta: [0.1,0.1] # uniform => None, beta => [a,b] U-shape [0.1,0.1] Uniform [1.,1.] falling [0.2,0.5] rising [0.2,0.5]
  signal_to_background_ratio: "" # "_1to4" # used for smote augmentation
  ratio_testing_vs_training: 1/40
  plot_after: 200


simulation_settings:
  theta_headers: ["radius","thickness","npanels","theta","length"]
  phi_labels: ["r_0[m]","z_0[m]","time_t[ms]","r_t[m]","z_t[m]","L_t[m]","ln(E0vsET)","edep_t[eV]","nsec"]
  target_headers: ["nC_Ge77"]
  target_range: [0,1]
  signal_condition: ["nC_Ge77==1"]
  weights_labels: ["nC_Ge77_scaling"]
  # Set parameter boundaries
  theta_min: [0,0,0,0,0]
  theta_max: [265,20,360,90,150]
  theta_fixed: [160, 2, 40, 45, 20]
  lf_cost: 1
  hf_cost: 2000



path_settings:
  version: v1.6
  path_to_files_train: ../legend-neutron-moderator/in/data/lf/
  path_to_files_predict: ["../legend-neutron-moderator/in/data/lf/","../legend-neutron-moderator/in/data/hf/"]
  iteration: [0,0]
  fidelity: [0,1]
  path_to_files_validation: ../legend-neutron-moderator/out/cnp/cnp_v1.6_output_validation.csv
  path_out_cnp:  ../legend-neutron-moderator/out/cnp
  path_out_mfgp:  ../legend-neutron-moderator/out/mfgp
  path_out_pce: ../legend-neutron-moderator/out/pce